### ISSUE TITLE
How to use multiple entities in Python.

### ISSUE THREAD

**Issue by swathionchip** [hellohaptik/chatbot_ner#275]
Hi,

How to use multiple entities in Python.

**_Example:_** 

entities = ['date','time','restaurant']
message = "Reserve me a table today at 6:30pm at Mainland China and on Monday at 7:00pm at Barbeque Nation" 

Thanks In advance.

Regards,
Swathi.

**Comment by swathionchip** [comment]
Could you please send reply.

**Comment by swathionchip** [comment]
Hi,

I wrote Sample Application In python but I am getting Error.

### **_Example :_**

from ner_v1.chatbot.entity_detection import get_text
from ner_v2.detectors.temporal.date.date_detection import DateAdvancedDetector
from ner_v2.detectors.temporal.time.time_detection import TimeDetector

message = "Reserve me a table today at 6:30pm at Mainland China and on Monday at 7:00pm at Barbeque Nation" 
entity_name = ['date','time','restaurant']
structured_value=None
fallback_value=None
bot_message=None
source_language='en'
timezone='UTC'
past_date_referenced=False 

output_res = get_text(message=message, entity_name=entity_name[2],
                  structured_value=structured_value,
                  fallback_value=fallback_value,
                  bot_message=bot_message,language=source_language)

detector = TimeDetector(entity_name=entity_name[1], language=source_language,
                        timezone=timezone)  
output_time = detector.detect(message=message, entity_name=entity_name[1],
                         structured_value=structured_value,
                         fallback_value=fallback_value)
detector = DateAdvancedDetector(entity_name='date',language=source_language,
                               timezone=timezone, 
                               past_date_referenced=past_date_referenced)
output_date = detector.detect(message=message, entity_name='date',
                         structured_value=structured_value,
                         fallback_value=fallback_value)

**_Below is the Error of the Above lines:_**

Traceback (most recent call last):
  File "3.py", line 33, in <module>
    fallback_value=fallback_value)
  File "../ner_v2/detectors/temporal/date/date_detection.py", line 717, in detect
    entity_list, original_text_list = self.detect_entity(text=text)
  File "../ner_v2/detectors/temporal/date/date_detection.py", line 140, in detect_entity
    date_data = self._detect_date()
  File "../ner_v2/detectors/temporal/date/date_detection.py", line 161, in _detect_date
    date_dict_list = self._detect_any_date()
  File "../ner_v2/detectors/temporal/date/date_detection.py", line 396, in _detect_any_date
    date_dict_list = self._date_dict_from_text(text=self.processed_text)
  File "../ner_v2/detectors/temporal/date/date_detection.py", line 477, in _date_dict_from_text
    date_list, original_list = self._date_value(text=text)
  File "../ner_v2/detectors/temporal/date/date_detection.py", line 504, in _date_value
    date_list, original_list = self.date_detector_object.detect_entity(text)
  File "../ner_v2/detectors/temporal/date/date_detection.py", line 828, in detect_entity
    self.date, self.original_date_text = self.language_date_detector.detect_date(self.processed_text)
  File "../ner_v2/detectors/temporal/date/en/date_detection.py", line 117, in detect_date
    date_list, original_list = self.get_exact_date(date_list, original_list)
  File "../ner_v2/detectors/temporal/date/en/date_detection.py", line 174, in get_exact_date
    date_list, original_list = self._gregorian_month_day_format(date_list, original_list)
  File "../ner_v2/detectors/temporal/date/en/date_detection.py", line 710, in _gregorian_month_day_format
    if self.now_date.month > mm:
TypeError: '>' not supported between instances of 'int' and 'NoneType'
1.txt: command not found


Regards,
Swathi.

**Comment by swathionchip** [comment]
Hi,

Could you please replay ASAP. We are Waiting for your response because we stucked here.

Regards,
Swathi.
